name: Shellcheck

on:
  pull_request:
    branches:
      - master

permissions: {}

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: debian-trixie
    permissions: {}
    steps:
      - uses: https://github.com/actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - name: Run ShellCheck
        uses: https://github.com/ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # 2.0.0
        env:
          SHELLCHECK_OPTS: -x # allow outside sources
