name: Shellcheck

on:
  pull_request:
    branches:
      - master

permissions: {}

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: debian-trixie
    permissions: {}
    steps:
      - uses: https://data.forgejo.org/actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v4
        with:
          persist-credentials: false
      - name: Run ShellCheck
        uses: https://github.com/ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # 2.0.0
        env:
          SHELLCHECK_OPTS: -x # allow outside sources
