name: Update Tools

on:
  # Manually triggerable only.
  workflow_dispatch:

# Permissions needed for GITHUB_TOKEN to create PR.
permissions:
  contents: write
  pull-requests: write

jobs:
  update-tools:
    runs-on: debian-trixie
    steps:
      - uses: https://github.com/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Update tools
        uses: ./actions/update-tools
