name: Workflow Security Analysis

on:
  pull_request:
    paths:
      - '.github/**'
  schedule:
    - cron: "0 0 * * 1" # Run every Monday at midnight
  workflow_dispatch:

permissions: {}

jobs:
  zizmor:
    runs-on: debian-trixie
    steps:
      - uses: https://data.forgejo.org/actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6
        with:
          persist-credentials: false
      - uses: ./actions/setup-rbmt
        with:
          rbmt-path: cargo-rbmt
          repo-url: ${{ forgejo.event.pull_request.head.repo.clone_url }}
      - run: cargo rbmt tools
      - run: zizmor .
