name: Workflow Security Analysis

on:
  pull_request:
    paths:
      - '.github/**'
  schedule:
    - cron: "0 0 * * 1" # Run every Monday at midnight
  workflow_dispatch:

permissions: {}

jobs:
  zizmor:
    runs-on: debian-trixie
    steps:
      - uses: https://github.com/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - uses: ./actions/setup-rbmt
        with:
          rbmt-version: ${{ forgejo.sha }}
          repo-url: ${{ forgejo.event.pull_request.head.repo.clone_url }}
      - run: cargo rbmt tools
      - run: zizmor .
