# This justfile is functional for cargo-rbmt, but also showcases a pattern for
# how to integrate rbmt into a justfile.
#
# The generic `_rbmt` recipe handles lock file selection (existing, recent,
# minimal) and installation of rbmt. Toolchain selection is handled internally
# by rbmt.
#
# Specific recipes (`lint`, `test`) call the generic `_rbmt` recipe with
# appropriate defaults.

# List available recipes.
_default:
    @just --list

# Install rbmt from the local workspace path.
@install:
    cargo install --quiet --path .

# Install workspace toolchains.
@toolchains: install
    RBMT_LOG_LEVEL=quiet cargo rbmt toolchains > /dev/null

# Run CI tasks using rbmt.
@_rbmt task lock="existing": install toolchains
    RBMT_LOG_LEVEL=quiet cargo rbmt --lock-file {{lock}} {{task}}

# Format files.
@fmt: (_rbmt "fmt")

# Lint with clippy.
@lint: (_rbmt "lint")

# Run tests.
@test: (_rbmt "test stable")

# Run tests with MSRV.
@msrv: (_rbmt "test msrv")

# Update Cargo-minimal.lock and Cargo-recent.lock files.
@lock: (_rbmt "lock")
