# This justfile is functional for cargo-rbmt, but also showcases
# a pattern for how to integrate rbmt into a justfile.

# List available recipes.
_default:
    @just --list

# Install rbmt from the local workspace path.
[group('system')]
@install:
    cargo install --quiet --path .

# Install workspace toolchains.
[group('system')]
@toolchains: install
    RBMT_LOG_LEVEL=progress cargo rbmt toolchains

# Setup rbmt and run with given args.
@rbmt *args: toolchains
    RBMT_LOG_LEVEL=progress cargo rbmt {{args}}

# Build and open docs.
@docs: (rbmt "docsrs --open")

# Format files.
@fmt: (rbmt "fmt")

# Lint with clippy.
@lint: (rbmt "lint")

# Run tests.
@test: (rbmt "test")

# Update Cargo-minimal.lock and Cargo-recent.lock files.
@lock: (rbmt "lock")
