name: 'Setup rbmt'
description: |
  Install cargo-rbmt.
inputs:
  rbmt-path:
    description: 'Filesystem path to cargo-rbmt crate to install from. If provided, installs from this path.'
    required: false

runs:
  using: "composite"
  steps:
    - name: Install cargo-rbmt
      shell: bash
      env:
        RBMT_PATH: ${{ inputs.rbmt-path }}
      run: |
        if [ -n "$RBMT_PATH" ]; then
          cargo install --locked --path "$RBMT_PATH"
        else
          RBMT_VERSION=$(cat rbmt-version)
          cargo install --locked --git https://git.rust-bitcoin.org/rust-bitcoin/rust-bitcoin-maintainer-tools --rev "$RBMT_VERSION"
        fi

    - name: Install toolchains
      shell: bash
      run: cargo rbmt toolchains
