name: 'Setup rbmt'
description: |
  Install environment dependencies for cargo-rbmt testing including cargo-rbmt itself.
inputs:
  toolchains:
    description: 'Rust toolchain versions, comma-separated (nightly,1.74.0)'
    required: false
    default: 'stable'
  components:
    description: 'Additional Rust components, comma-separated (clippy,rustfmt)'
    required: false
    default: ''
  rbmt-version:
    description: 'Git ref (commit, tag, or branch) of cargo-rbmt to install'
    required: false
    default: 'master'

runs:
  using: "composite"
  steps:
    # Cache ARM toolchain apt packages for faster subsequent runs.
    - name: Cache ARM toolchain packages
      uses: actions/cache@v5
      with:
        path: /var/cache/apt/archives
        key: ${{ runner.os }}-apt-arm-toolchain-v1
        restore-keys: |
          ${{ runner.os }}-apt-arm-toolchain-

    # Setup Rust with automatic caching of toolchains and build artifacts.
    # Always install stable for cargo-rbmt, plus the requested toolchain.
    - name: Setup Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable,${{ inputs.toolchains }}
        components: rust-src,${{ inputs.components }}
        # ARM target to test no-std build.
        target: thumbv7m-none-eabi

    # Install ARM cross-compiler for no-std testing.
    - name: Install ARM cross-compiler
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi
        echo "CC_thumbv7m_none_eabi=arm-none-eabi-gcc" >> $GITHUB_ENV

    # Install cargo-rbmt using stable toolchain.
    - name: Install cargo-rbmt
      shell: bash
      run: |
        cargo +stable install --git https://github.com/rust-bitcoin/rust-bitcoin-maintainer-tools.git --rev ${{ inputs.rbmt-version }} cargo-rbmt --locked
