name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  dogfood-lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Dogfood with cargo-rbmt
        uses: ./.github/actions/setup-rbmt
        with:
          rbmt-version: ${{ github.sha }}

      - name: Run lint on workspace
        run: cargo rbmt --lock-file existing lint

      - name: Build documentation (stable)
        run: cargo rbmt --lock-file existing docs

      - name: Build documentation (docs.rs / nightly)
        run: cargo rbmt --lock-file existing docsrs

  dogfood-test-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lock-file: [existing, recent, minimal]
        toolchain: [stable, msrv]
    steps:
      - uses: actions/checkout@v6

      - name: Dogfood with cargo-rbmt
        uses: ./.github/actions/setup-rbmt
        with:
          rbmt-version: ${{ github.sha }}

      - name: Run tests (${{ matrix.toolchain }}, ${{ matrix.lock-file }} lock)
        run: cargo rbmt --lock-file ${{ matrix.lock-file }} test --toolchain ${{ matrix.toolchain }}
